"""create email threads table

Revision ID: 33c39c5e2f79
Revises:
Create Date: 2026-07-21 20:17:22.449703

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "33c39c5e2f79"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_threads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("gmail_thread_id", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=998), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=False),
        sa.Column("participants", sa.Text(), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("latest_message_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_threads_gmail_thread_id"), "email_threads", ["gmail_thread_id"], unique=True
    )
    op.create_index(
        op.f("ix_email_threads_latest_message_at"),
        "email_threads",
        ["latest_message_at"],
        unique=False,
    )
    op.create_index(op.f("ix_email_threads_user_id"), "email_threads", ["user_id"], unique=False)
    op.create_index(
        "ix_email_threads_user_latest",
        "email_threads",
        ["user_id", "latest_message_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_email_threads_user_latest", table_name="email_threads")
    op.drop_index(op.f("ix_email_threads_user_id"), table_name="email_threads")
    op.drop_index(op.f("ix_email_threads_latest_message_at"), table_name="email_threads")
    op.drop_index(op.f("ix_email_threads_gmail_thread_id"), table_name="email_threads")
    op.drop_table("email_threads")
    # ### end Alembic commands ###
