"""create email messages table

Revision ID: 604d1227515f
Revises: 33c39c5e2f79
Create Date: 2026-07-21 22:27:13.600737

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "604d1227515f"
down_revision: str | Sequence[str] | None = "33c39c5e2f79"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("gmail_message_id", sa.String(length=255), nullable=False),
        sa.Column("sender", sa.String(length=998), nullable=False),
        sa.Column("recipients", sa.Text(), nullable=False),
        sa.Column("cc", sa.Text(), nullable=False),
        sa.Column("subject", sa.String(length=998), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column("body_html", sa.Text(), nullable=False),
        sa.Column("attachment_metadata", sa.JSON(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["thread_id"], ["email_threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_messages_gmail_message_id"),
        "email_messages",
        ["gmail_message_id"],
        unique=True,
    )
    op.create_index(op.f("ix_email_messages_sent_at"), "email_messages", ["sent_at"], unique=False)
    op.create_index(
        op.f("ix_email_messages_thread_id"), "email_messages", ["thread_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_email_messages_thread_id"), table_name="email_messages")
    op.drop_index(op.f("ix_email_messages_sent_at"), table_name="email_messages")
    op.drop_index(op.f("ix_email_messages_gmail_message_id"), table_name="email_messages")
    op.drop_table("email_messages")
    # ### end Alembic commands ###
