"""create thread analysis tables

Revision ID: 781afa20f709
Revises: 25b0aec26dbb
Create Date: 2026-08-05 14:10:39.091807

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "781afa20f709"
down_revision: str | Sequence[str] | None = "25b0aec26dbb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thread_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("source_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("sentiment", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["thread_id"], ["email_threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_thread_analyses_source_fingerprint"),
        "thread_analyses",
        ["source_fingerprint"],
        unique=False,
    )
    op.create_index(
        "ix_thread_analyses_thread_created",
        "thread_analyses",
        ["thread_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_thread_analyses_thread_id"), "thread_analyses", ["thread_id"], unique=False
    )
    op.create_table(
        "action_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("owner", sa.String(length=320), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["analysis_id"], ["thread_analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_action_items_analysis_id"), "action_items", ["analysis_id"], unique=False
    )
    op.create_index(op.f("ix_action_items_due_at"), "action_items", ["due_at"], unique=False)
    op.create_index(op.f("ix_action_items_status"), "action_items", ["status"], unique=False)
    op.create_table(
        "suggested_replies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("tone", sa.String(length=50), nullable=False),
        sa.Column("subject", sa.String(length=998), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["analysis_id"], ["thread_analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_suggested_replies_analysis_id"), "suggested_replies", ["analysis_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_suggested_replies_analysis_id"), table_name="suggested_replies")
    op.drop_table("suggested_replies")
    op.drop_index(op.f("ix_action_items_status"), table_name="action_items")
    op.drop_index(op.f("ix_action_items_due_at"), table_name="action_items")
    op.drop_index(op.f("ix_action_items_analysis_id"), table_name="action_items")
    op.drop_table("action_items")
    op.drop_index(op.f("ix_thread_analyses_thread_id"), table_name="thread_analyses")
    op.drop_index("ix_thread_analyses_thread_created", table_name="thread_analyses")
    op.drop_index(op.f("ix_thread_analyses_source_fingerprint"), table_name="thread_analyses")
    op.drop_table("thread_analyses")
    # ### end Alembic commands ###
